kind: ConfigMap
apiVersion: v1
metadata:
  name: trustyai-service-operator-config
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: trustyai
    app.opendatahub.io/trustyai: 'true'
    platform.opendatahub.io/part-of: trustyai
  annotations:
    opendatahub.io/managed: 'false'
    platform.opendatahub.io/instance.name: default-trustyai
    internal.config.kubernetes.io/previousNamespaces: default
    internal.config.kubernetes.io/previousKinds: ConfigMap
    platform.opendatahub.io/instance.generation: '1'
    internal.config.kubernetes.io/previousNames: trustyai-service-operator-config
    platform.opendatahub.io/version: 3.0.0
    platform.opendatahub.io/type: OpenShift AI Self-Managed
data:
  kServeServerless: enabled
  ragas-provider-image: 'registry.redhat.io/rhoai/odh-trustyai-ragas-lls-provider-dsp-rhel9@sha256:c1694891f19be1fe1abd431505549dc02021c389e640e77877bbb7921b42aa5b'
  lmes-detect-device: 'true'
  guardrails-orchestrator-image: 'quay.io/ckavili/fms-guardrails-orchestrator:race-fix'
  garak-provider-image: 'quay.io/trustyai/llama-stack-provider-trustyai-garak:latest'
  lmes-image-pull-policy: Always
  trustyaiOperatorImage: 'quay.io/trustyai/trustyai-service-operator:f0db9fbede82ee354a3e5a53d2bcc313b111a234'
  trustyaiServiceImage: 'registry.redhat.io/rhoai/odh-trustyai-service-rhel9@sha256:1431c04ecb88387a9e15566ba8105d19c7fbceecf65eb5731fe69cccbeb09cf5'
  guardrails-sidecar-gateway-image: 'quay.io/trustyai/guardrails-sidecar-gateway:latest'
  lmes-pod-checking-interval: 10s
  kube-rbac-proxy: 'registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:657bc0b43fe2da3211d80dc5085f57dccb451c30b1a254b87b4876745c414d36'
  lmes-driver-image: 'registry.redhat.io/rhoai/odh-ta-lmes-driver-rhel9@sha256:a59bb87677721dbadaa3e88e29d47470d0afa2c1b52c652caa77f74466beb698'
  lmes-allow-online: 'false'
  lmes-pod-image: 'registry.redhat.io/rhoai/odh-ta-lmes-job-rhel9@sha256:4000a91132d67503a4691e76a7079f9140e3c8091fb1a59ad235446f96cb1a34'
  lmes-allow-code-execution: 'false'
  lmes-max-batch-size: '24'
  guardrails-built-in-detector-image: 'quay.io/trustyai/guardrails-detector-built-in:latest'
  lmes-default-batch-size: '8'
